apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: todogi-backend
  namespace: todogi-be
spec:
  entryPoints:
    - websecure
  routes:
    - match: (Host(`api.singlestranger.com`) || Host(`www.api.singlestranger.com`)) && PathPrefix(`/api`)
      kind: Rule
      priority: 100
      services:
        - name: todogi-be
          port: 8080
  tls:
    secretName: todogi-backend-tls
