apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: todogi
  namespace: todogi-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`todogi.singlestranger.com`) || Host(`www.todogi.singlestranger.com`)
      kind: Rule
      services:
        - name: todogi-expo-app
          port: 80
  tls:
    secretName: todogi-app-tls
