apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: auth-gateway
  namespace: gateway
spec:
  entryPoints:
    - websecure
  routes:
    - match: (Host(`auth.cantalay.com`) || Host(`www.auth.cantalay.com`)) && PathPrefix(`/auth`)
      kind: Rule
      priority: 50
      services:
        - name: auth-gateway
          port: 8080
  tls:
    secretName: auth-gateway-tls
